name: docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: build
        run: go build -o app

      - name: Log Into Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Image
        run: docker build . --tag ghcr.io/${GITHUB_REPOSITORY}:latest --cache-from ghcr.io/${GITHUB_REPOSITORY}:latest

      - name: Push Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push ghcr.io/${GITHUB_REPOSITORY}:latest
